

# Find the Difference

# You are given two strings s and t.

# String t is generated by random shuffling string s and 
# then add one more letter at a random position.

# Return the letter that was added to t.

# Input: s = "abcd", t = "abcde"
# Output: "e"


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        freq = {} # O(1) 
        
        for char in s: 
            freq[char] = 1 + freq.get(char, 0)
            
        for ch in t:
            if ch not in freq or freq[ch] == 0:
                return ch
            else:
                freq[ch] -= 1
            
# s = ""  t = "a"
